// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogintestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logintest() {
    // Test name: login test
    // Step # | name | target | value
    // 1 | open | https://accounts.google.com/ServiceLogin/signinchooser?passive=1209600&continue=https%3A%2F%2Faccounts.google.com%2F&followup=https%3A%2F%2Faccounts.google.com%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin | 
    driver.get("https://accounts.google.com/ServiceLogin/signinchooser?passive=1209600&continue=https%3A%2F%2Faccounts.google.com%2F&followup=https%3A%2F%2Faccounts.google.com%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin");
    // 2 | setWindowSize | 669x691 | 
    driver.manage().window().setSize(new Dimension(669, 691));
    // 3 | assertTitle | Sign in - Google Accounts | 
    assertThat(driver.getTitle(), is("Sign in - Google Accounts"));
    // 4 | click | css=.JDAKTe:nth-child(1) .w1I7fb | 
    driver.findElement(By.cssSelector(".JDAKTe:nth-child(1) .w1I7fb")).click();
    // 5 | type | name=password | Indiana2000!
    driver.findElement(By.name("password")).sendKeys("Indiana2000!");
    // 6 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 7 | click | css=#passwordNext .RveJvd | 
    driver.findElement(By.cssSelector("#passwordNext .RveJvd")).click();
  }
}
